### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by techtoys**
Developing a smartwatch with ESP32 + 1.54" MIPI display + LittlevGL. This is the first step.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Will it be a complete Smartwatch project or "just" some examples?

**Comment by techtoys** [comment]
Gabor

Will be a complete smartwatch, at least the time will tick with digital clock format 12:30 ->12:31, etc. Bonus features are heart rate measurement, vibrator switching, and BLE and Wifi connection with smart phone. CMOS camera is also available. But a preliminary test from [github ](https://github.com/igrr/esp32-cam-demo) to stream it via http is very slow and unstable. I think the bottleneck is the http-wifi connection. If I can update the cmos framebuffer to the LCD it would be much faster. 

Not sure if all features could be finished by myself. At the end it will be hardware and software opensource so I hope somebody more expertise will fork it and improve. 

Just finished the LCD part for Arduino in this minute. Will port them for LittlevGL tomorrow. Please hold it 1-2 days to do a real Pull.

Let me know your thought.

John

**Comment by kisvegabor** [comment]
Happy to hear that it will be a complete project!

I suggest storing this project in your personal account because:
- It will be easier for you to update the project
- Here (in LittelvGL organization) there are  "only" examples and not full projects
- It will bring reputation to you! :) 

If already there is something to show in the project I can add links to it various places:
- https://littelvgl.com
- https://blog.littlevgl.com/2018-12-26/references
- The main README here

How does it sounds to you?

**Comment by techtoys** [comment]
It sounds good. I believe https://littlevgl.com is a better place. Have just finished the first demo for Arduino, but I find it mandatory to structure the program into a particular way to make it work. They are :<br>
(1) Need to put all GUI related functions into a .cpp file and then pin that task to a core for esp32, in my case it is GuiTask.cpp. Conventional Arduino program structure is like <br>

```
setup()
...
loop()
```

Program structure like this doesn't work although it compiles OK and download OK too. I believe it is due to the particular RTOS related features for esp32 arduino core.

(2) Another issues you may not like it is that, I have made a new folder `lv_drivers` in the same root as lvgl.h in order to let the Arduino IDE know such drivers exist for CTP and new LCD driver.
Something like this screen shot:
image<br>
Don't know other location that allow folder discovery for Arduino!

(3) Complete esp32_littlevgl_hello demo and the drivers area available from my dropbox. If you are interested (and have time) please download and take a look.
[esp32_littlevgl_hello](https://www.dropbox.com/sh/99unv2ytkzygr6h/AADoJ5h1eD5TScjehjb-SIJta?dl=0)<br>
[lv_drivers](https://www.dropbox.com/sh/s5wm7cmokopci7r/AAA_irc6NL0R7qATBb21N-r6a?dl=0)<br>
[lv_conf](https://www.dropbox.com/s/si426qqpa46lpib/lv_conf.h?dl=0)

**Comment by kisvegabor** [comment]
For the directory structure:
Would it work if - similarly to `lvgl` - you create new libraries from `lv_examples` and `lv_drivers`?

**Comment by techtoys** [comment]
It works if I make all drivers outside littlevgl folder in arduino libraries. Folder structure now looks like this:<br>

<pre>
\Arduino libraries
		\littlevlg
			library.properties
			lv_conf.h
			\src
		\lv_drivers
			library.properties
			\src
			&nbsp;&nbsp;&nbsp;display.c
			&nbsp;&nbsp;&nbsp;display.h
			&nbsp;&nbsp;&nbsp;indev.c
			&nbsp;&nbsp;&nbsp;indev.h
			\examples
</pre>
							
I believe it is the preferred folder structure because the lv_drivers becomes a stand-alone project folder and at the same time compatible with littlevgl. Good to avoid messing up when there is any update. 
From time to time I see some people asking for instruction guide to integrate Arduino with Littlevgl, specially for ESP32. Maybe a blog to summarize what I found is good?

**Comment by kisvegabor** [comment]
Awesome, the structure looks much better.

> Maybe a blog to summarize what I found is good?

Absolutely yes! I'd be very very welcome :)

If you moved the files to your repository (as discussed above) please close this PR.

**Comment by techtoys** [comment]
Thanks a lot. You work so hard, early in the morning. Will let you know once I have finished the new blog. It will be like chapter 2 of the first iPod nano6 hacking blog.

**Comment by kisvegabor** [comment]
> You work so hard, early in the morning.

A lot of emails were accumulated on the weekend :)

> Will let you know once I have finished the new blog. It will be like chapter 2 of the first iPod nano6 hacking blog.

Great! :)

**Pull request closed without merging**
