### PR TITLE
Attempt to make standard Arduino library format

### PR DESCRIPTION
**Pull request by Pablo2048**
Hi,
as I promised here http://forum.littlevgl.com/viewtopic.php?f=12&t=29&sid=1f49e4aa570ac2d4e205e3b7205fc858 this is my attempt to create Arduino library for LittlevGL. It has following features:
  * able to be installed as .ZIP library (after we create an release)
  * able to be installed via Library manager (more on needed stepls later)
  * able to be used in PlatformIO (this need to be checked)

There are things that I want to discuss:
  * library uses lvgl as submodule which is IMHO not very optimal - version of the library has to be the same as version of lvgl and this is hard to maintain. My suggestion - at every lvgl release, copy the lvgl folder into src folder in this library, modify lv_conf.h if needed and modify json/properties file with _right_ lvgl version OR made separate version numbers for this library and lvgl.
  * I've put myself into .properties file as an maintainer of this library because i want to remove some load from Gabor to maintain just this small part of the project.

Things that has to be done after this PR get merged:
  * We need to create tag with version number
  * We need to create Release
  * after first two steps are done everyone can install this library as .ZIP from Releases page
 * We need to continue as described here https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager and create issue here https://github.com/arduino/Arduino/issues and after few days LVGL library will be registered and can be installed in Arduino IDE via the Library manager.

Any comments are welcome...

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

It's awesome!

> library uses lvgl as submodule which is IMHO not very optimal - version of the library has to be the same as version of lvgl and this is hard to maintain. My suggestion - at every lvgl release, copy the lvgl folder into src folder in this library, modify lv_conf.h if needed and modify json/properties file with right lvgl version OR made separate version numbers for this library and lvgl.

Updating to the new version of lvgl after a fix in master is easier with submodules but if in this case, it make things more complicated then I'm fine with no-submoule too. 

> I've put myself into .properties file as an maintainer of this library because i want to remove some load from Gabor to maintain just this small part of the project.

Thank you very much! If you want I can give you write access to this repo.

**Comment by Pablo2048** [comment]
Hi,
> Updating to the new version of lvgl after a fix in master is easier with submodules but if in this case, it make things more complicated then I'm fine with no-submoule too.

Ok, I will made a change in the repository to include LVGL v5.3 as an starting point

> 
> > I've put myself into .properties file as an maintainer of this library because i want to remove some load from Gabor to maintain just this small part of the project.
> 
> Thank you very much! If you want I can give you write access to this repo.

Thanks - this will be perfect...

**Comment by Pablo2048** [comment]
One more thing that I forgot to mention - library name. I strongly suggest to rename this repository from just plain `arduino` to something like `lvgl_arduino`...

**Comment by kisvegabor** [comment]
@Pablo2048 
I've sent the invitation and renamed the repo.

**Comment by Pablo2048** [comment]
@kisvegabor Thank you. I did some modifications - added example photo, environment versions etc. so please take a look. I've also changed version # to 1.0.0 because I need the opportunity to add new examples and/or fix errors in the examples. If you are ok with this and give me a green light, then I'll do a merge and all necessary steps to make an release.

**Comment by kisvegabor** [comment]
Awesome!

I pulled the changes and it seems `lvgl` is added twice:
image

**Comment by Pablo2048** [comment]
Well, it seems like we need to manually remove the littlevgl folder after merge. In my branch this folder doesn't exist...

**Comment by kisvegabor** [comment]
Ok, we will see.

Merged!

**Comment by kisvegabor** [comment]
It was merged correctly. littlevgl/src is not existing.

Thank you very much for this update! I'm sure it will help a lot to Arduino users.

And also thank you for offering to maintain the repository. :) It really helps a lot!

**Comment by Pablo2048** [comment]
Great. Thank You. I've made release of version 1.0.0 . I'll test it and when everything is ok I'll made all steps to register this library in Arduino Library manager...

**Comment by kisvegabor** [comment]
Awesome! :clap: :clap: :clap:

**Pull request merged**
