### PR TITLE
added touchscreen support

### PR DESCRIPTION
**Pull request by imcort**

### CODE REVIEW

**Comment by Pablo2048** [comment]
This is not good idea - you didn't added touchscreen support, but replaced the encoder. Also you have modified the screen rotation without reason and added the button. Please create new example in examlpes folder...

**Review by embeddedt — CHANGES_REQUESTED** [review]
See @Pablo2048's comment. Replacing existing functionality is definitely a bad idea.

**Review by embeddedt — CHANGES_REQUESTED** [review]
Having another copy of the demo from `lv_examples` doesn't really make sense. It would be better to use something simple like the button you had (but only in your new example, not the ESP32_TFT_eSPI) one.

Also, please revert the changes you made to the `ESP32_TFT_eSPI` sketch.

**Comment by imcort** [comment]
Sorry, I'm new for this library, it seems the encoder doesn't make sense with the original example, so I tried to make the touchscreen work and added a button on the screen. I will close this pull request and write a new example.

**Comment by Pablo2048** [comment]
Ok. When You made the new example, please do some screenshots/photos and put it into ```extras`` folder - I'll modify the readme.md file to mention your new example and put links to the images so everyone can see what it does. Thanks.

**Pull request closed without merging**
