### PR TITLE
Added Night theme example

### PR DESCRIPTION
**Pull request by elgerg**
Hi,

Ive added the theme example to the arduino environment from:

https://github.com/littlevgl/lv_examples/blob/master/lv_tests/lv_test_theme/lv_test_theme_1.c

I hope that this helps someone else get started.

Kind regards
Alex

### CODE REVIEW

**Comment by embeddedt** [comment]
It would be preferable to avoid duplicating `lv_test_theme_1`, if possible. Now we will have two copies to maintain. :)

It would be better, IMO, to provide instructions on how Arduino users can copy examples from `lv_examples` themselves. That way the burden of updating is on the users, not us.

(An even better solution would be for the Arduino IDE to support submodules, but that's another story.)

**Comment by elgerg** [comment]
Good point.

How/where would i put that documentation?

Regards
Alex

**Comment by elgerg** [comment]
Looking at things, the only difference between the example and the arduino example file "tabs.ino" is the header and footer:
```c
/**
 * @file lv_test_theme_1.c
 *
 */

/*********************
 *      INCLUDES
 *********************/
#include "lv_test_theme_1.h"

#if LV_USE_TESTS
/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/


work..


#endif /*LV_USE_TESTS*/
```
Is there anyway gitub can strip this and push it to the other reop?

Regards
Alex

**Comment by embeddedt** [comment]
> Is there anyway gitub can strip this and push it to the other repo?

I don't think it can be done easily. It might be doable with Travis, but that's rather complex.

> How/where would i put that documentation?

A comment above `main` is probably sufficient, unless the Arduino IDE has a better way for showing that information.

**Comment by kisvegabor** [comment]
IMO, having 1-2 easy-to-try examples which needs to be maintained is acceptable. 
However, adding a lot of examples with a minor adjustment is really not reasonable.

**Comment by Pablo2048** [comment]
@elgerg You can put the steps into separate section in readme.md, or create howto.md file in the repository and put the steps here or (probably) we can turn on repository wiki and put all this here. Unfortunately ordinary Arduino IDE user probably don't know about github project wiki...

**Pull request closed without merging**
