### PR TITLE
Add support for Maixduino.

### PR DESCRIPTION
**Pull request by bitsk**
Maixduino makes the Arduino IDE and libraries support the Maix series of development boards (k210 chips).
Here is the project wiki : https://maixduino.sipeed.com/en/
This video shows the running effect : https://youtu.be/pLbBEXIQ9ys

### CODE REVIEW

**Review by Pablo2048 — CHANGES_REQUESTED** [review]
Please do not modify lv_conf.h file in library.

**Review by embeddedt — CHANGES_REQUESTED** [review]
It looks to me like this changes the repository to only support Maixduino, and not the original Arduino. These changes either need to be conditionally enabled, or need to be moved to a separate repository (@kisvegabor?).

**Comment by kisvegabor** [comment]
We should have a "basic Arduino" project. As @embeddedt suggested we can have a new repo for Maixduino. 

We need somebody who can maintain that repo (update lvgl on new releases, answer questions if any). @btx000 would you be interested in it?

**Comment by bitsk** [comment]
Yes, I am interested in maintaining a new repo.

**Comment by kisvegabor** [comment]
@btx000 Awesome! I've just created the new repo and granted write access.
https://github.com/littlevgl/lv_maixduino

Let's continue on that repo if there are any questions.

**Pull request closed without merging**
